root: true
extends:
  - zakodium/ts
  - zakodium/react
  - zakodium/unicorn
rules:
  'import/default': off
  'import/no-unresolved': off
  'react-refresh/only-export-components': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/no-implied-eval': off
  '@typescript-eslint/no-misused-promises': off
  '@typescript-eslint/restrict-plus-operands': off
  'react/no-unstable-nested-components': off
  react/no-unknown-property:
    - error
    - ignore:
        - 'css'
  unicorn/no-array-reduce: off
parserOptions:
  sourceType: module
