name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: "https://gitlab-etu.ing.he-arc.ch/isc/2022-23/niveau-3/3285-tb-il/281/pixelium.git"
          GIT_USERNAME: xavier.stouder
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
